version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: workflow_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - chromadb
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/workflow_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_KEY=${SERPAPI_KEY}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  chroma_data:
